### PR TITLE
dynamic near far

### PR DESCRIPTION
**Pull request by valentinMachado**
resolve https://github.com/VCityTeam/UD-Viz/issues/199

### CODE REVIEW

**Comment by agrignard** [comment]
Great @valentinMachado . Hapy to give a review to this PR. Can you just tell me how I can test this zoom behavior?

**Comment by valentinMachado** [comment]
@agrignard first you should pull this branch, then host the repo with a local server on your computer or follow  "Running the examples" section of the Ud-Viz ReadMe then open localhost:8000 on your web browser. This will give you the possibility to test examples based on the code of this branch.

**Comment by agrignard** [comment]
OK I ave pull tis branch and run ```npm run build``` 

but I get the follwoing error
````
arno@wu-pers-03740 UD-Viz % npm run build

> ud-viz@2.37.3 build
> cross-env NODE_ENV=production webpack --config=./config/webpack.config.js

Hash: cadefc383c08d979ea85
Version: webpack 4.46.0
Time: 19615ms
Built at: 05/24/2022 11:49:45 AM
 Asset      Size  Chunks  Chunk Names
udv.js  2.97 MiB       0  main
Entrypoint main = udv.js
  [0] ./node_modules/three/src/three.js 496 bytes {0} [built] [failed] [1 error]
  [1] ./node_modules/three/build/three.module.js 1.11 MiB {0} [built]
  [2] ./node_modules/@babel/runtime/helpers/interopRequireDefault.js 225 bytes {0} [built]
  [3] ./node_modules/@babel/runtime/helpers/typeof.js 723 bytes {0} [built]
  [9] ./node_modules/itowns/lib/Core/Geographic/Coordinates.js 10.8 KiB {0} [built]
 [10] ./node_modules/itowns/lib/Main.js 19.5 KiB {0} [built]
 [12] ./node_modules/itowns/lib/Core/Geographic/Extent.js 25.4 KiB {0} [built]
 [13] ./node_modules/proj4/lib/index.js + 89 modules 198 KiB {0} [built]
      | ./node_modules/proj4/lib/index.js 612 bytes [built]
      | ./node_modules/proj4/lib/defs.js 1.11 KiB [built]
      | ./node_modules/proj4/lib/nadgrid.js 5.04 KiB [built]
      | ./node_modules/proj4/lib/Proj.js 2.35 KiB [built]
      | ./node_modules/proj4/lib/common/toPoint.js 200 bytes [built]
      | ./node_modules/proj4/lib/transform.js 2.49 KiB [built]
      | ./node_modules/proj4/lib/core.js 2.41 KiB [built]
      | ./node_modules/mgrs/mgrs.js 20.5 KiB [built]
      | ./node_modules/proj4/lib/Point.js 894 bytes [built]
      | ./node_modules/proj4/projs.js 2.23 KiB [built]
      | ./node_modules/proj4/lib/global.js 691 bytes [built]
      | ./node_modules/proj4/lib/constants/values.js 1.27 KiB [built]
      | ./node_modules/proj4/lib/match.js 444 bytes [built]
      | ./node_modules/proj4/lib/projString.js 3.25 KiB [built]
      | ./node_modules/wkt-parser/index.js 6.4 KiB [built]
      |     + 75 hidden modules
 [16] ./node_modules/itowns/lib/Core/Geographic/Crs.js 3.92 KiB {0} [built]
 [18] ./src/Game/Game.js 1.29 KiB {0} [built]
 [20] ./src/Game/GameObject/Components/LocalScript.js 3.42 KiB {0} [built]
 [21] ./node_modules/jquery/dist/jquery.js 282 KiB {0} [built]
 [23] ./node_modules/itowns/lib/Source/Source.js 11.5 KiB {0} [built]
[284] multi ./src/index.js 28 bytes {0} [built]
[437] ./src/index.js + 271 modules 773 KiB {0} [built]
      | ./src/index.js 1.3 KiB [built]
      | ./src/Components/Components.js 377 bytes [built]
      | ./src/Widgets/Widgets.js 1.06 KiB [built]
      | ./src/Views/Views.js 222 bytes [built]
      | ./src/Templates/Templates.js 966 bytes [built]
      | ./node_modules/three/examples/jsm/controls/OrbitControls.js 25.5 KiB [built]
      | ./node_modules/three/examples/jsm/controls/TransformControls.js 39.7 KiB [built]
      | ./node_modules/three/examples/jsm/geometries/ConvexGeometry.js 1.14 KiB [built]
      | ./node_modules/three/examples/jsm/postprocessing/ShaderPass.js 1.42 KiB [built]
      | ./node_modules/three/examples/jsm/postprocessing/EffectComposer.js 6.28 KiB [built]
      | ./node_modules/three/examples/jsm/postprocessing/RenderPass.js 1.71 KiB [built]
      | ./src/Components/Request/RequestService.js 3.4 KiB [built]
      | ./src/Components/SystemUtils/SystemUtils.js 65 bytes [built]
      | ./src/Components/WebSocketService.js 2.08 KiB [built]
      | ./src/Components/3DTiles/TilesManager.js 13.8 KiB [built]
      |     + 257 hidden modules
    + 718 hidden modules

ERROR in ./node_modules/three/src/three.js 110:9
Module parse failed: Unexpected token (110:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { Interpolant } from './math/Interpolant.js';
| export { Triangle } from './math/Triangle.js';
> export * as MathUtils from './math/MathUtils.js';
| export { Spherical } from './math/Spherical.js';
| export { Cylindrical } from './math/Cylindrical.js';
 @ ./node_modules/three/examples/jsm/postprocessing/ShaderPass.js 1:0-4:15 15:25-39 23:19-32 25:23-37
 @ ./src/index.js
 @ multi ./src/index.js
`````

**Comment by agrignard** [comment]
OK great, the near far now work and we are able to zoom out without having the scene disappearing.

I am personally find with this PR. I guess we let @EricBoix merge it?

**Pull request merged**
