### PR TITLE
fix by reading client instead of offset

### PR DESCRIPTION
**Pull request by valentinMachado**

### CODE REVIEW

**Review by mathieuLivebardon — APPROVED** [review]
🖱️🔥🦊

**Review by mathieuLivebardon — CHANGES_REQUESTED** [review]
Example doesn't work in production mode 
image

- `npm run start`
- Open `http://localhost:8000/packages/browser/examples/MultiPlayerGamePlanar.html`

**Comment by valentinMachado** [comment]
> Example doesn't work in production mode image
> 
> * `npm run start`
> * Open `http://localhost:8000/packages/browser/examples/MultiPlayerGamePlanar.html`

Yeah the host script was not launching the game socket service, but this is going to be fixed by https://github.com/VCityTeam/UD-Viz/pull/542 that should be reviewed in priority

**Review by mathieuLivebardon — APPROVED** [review]
👌

**Pull request merged**
